#!/bin/bash

SHOULD_KILL=true
MAX_DEPTH=3
EDITOR="zed"

while [[ "$#" -gt 0 ]]; do
	case "$1" in
		--nk)
			SHOULD_KILL=false
			;;
		--depth)
			shift
			MAX_DEPTH="$1"
			;;
		--e)
			shift
			EDITOR="$1"
				;;
		*)
			echo "Unknown parameter: $1" >&2
			exit 1
			;;
	esac
	shift
done

DIR=$(find ~/coding -maxdepth "$MAX_DEPTH" -type d | fzf)
[ -z "$DIR" ] && exit 1

case "$EDITOR" in
	zed)
		zeditor "$DIR" &
		;;
	code|vscode)
		code "$DIR" &
		;;
	*)
		echo "Invalid editor: $EDITOR"
		echo "Supported editors: zed, code"
		exit 1
		;;
esac

if $SHOULD_KILL; then
	hyprctl dispatch killwindow class:kitty
fi
